In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/

In [3]:
import sys
sys.path.append(os.path.abspath('/content/gdrive/My Drive/Thesis'))

In [4]:
df = pd.read_csv("gdrive/MyDrive/Thesis/csv/en_climate_monthly_AB_3050520_1887-1995_P1M.csv")

In [ ]:
#list(df.columns)

In [5]:
df.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Mean Max Temp (°C),Mean Max Temp Flag,Mean Min Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow Grnd Last Day (cm),Snow Grnd Last Day Flag,Dir of Max Gust (10's deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-115.57,51.18,BANFF,3050520,1887-01,1887,1,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN
1,-115.57,51.18,BANFF,3050520,1887-02,1887,2,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN
2,-115.57,51.18,BANFF,3050520,1887-03,1887,3,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN
3,-115.57,51.18,BANFF,3050520,1887-04,1887,4,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN
4,-115.57,51.18,BANFF,3050520,1887-05,1887,5,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#data = df[["Date/Time", "Mean Max Temp (°C)"]].copy()
data = df.copy()

In [7]:
data.columns = ["x", "y", "station", "climateID", "date_time",
                                              "year", "month", "mean_MAX_temp_C", "mean_MAX_temp_FLAG",
                                              "mean_MIN_temp_C", "mean_MIN_temp_FLAG", "MEAN_TEMP_C",
                                              "MEAN_TEMP_FLAG", "extr_MAX_temp_C", "extr_MAX_temp_FLAG",
                                              "extr_MIN_temp_C", "extr_MIN_temp_FLAG", "total_rain_mm",
                                              "total_rain_FLAG", "total_snow_cm", "total_snow_FLAG", 
                                              "total_precip_mm", "total_precip_FLAG", "snow_ground_last_day_cm",
                                              "snow_ground_FLAG", "dir_max_gust", "dir_max_gust_FLAG",
                                              "speed_max_gust_km_h", "speed_max_gust_FLAG"]

In [ ]:
#data.head()

In [8]:
data = data[~(data['date_time'] < '1900-01-01')]

In [9]:
data = data.drop(["x", "y", "station", "year", "month", "mean_MAX_temp_FLAG", "mean_MIN_temp_FLAG", "MEAN_TEMP_FLAG", 
                  "extr_MAX_temp_FLAG", "extr_MIN_temp_FLAG", "total_rain_FLAG", 
                  "total_snow_FLAG", "total_precip_FLAG", "snow_ground_FLAG", 
                  "dir_max_gust_FLAG", "speed_max_gust_FLAG", "climateID", "snow_ground_last_day_cm", 
                  "dir_max_gust", "speed_max_gust_km_h"],axis=1)

In [10]:
data.head()

,date_time,mean_MAX_temp_C,mean_MIN_temp_C,MEAN_TEMP_C,extr_MAX_temp_C,extr_MIN_temp_C,total_rain_mm,total_snow_cm,total_precip_mm
157,1900-02,-3.3,-14.7,-9.0,5.6,-36.7,0.0,16.5,16.5
158,1900-03,3.4,-8.1,-2.4,12.8,-25.6,25.1,42.9,68.1
159,1900-04,11.9,-1.3,5.3,21.7,-5.6,19.3,18.5,37.8
160,1900-05,16.2,1.3,8.8,20.6,-2.8,22.1,0.0,22.1
161,1900-06,20.4,5.4,12.9,29.4,-2.2,118.1,0.0,118.1

In [11]:
data.describe().transpose()

                  count       mean        std   min   25%   50%    75%    max
mean_MAX_temp_C  1129.0   8.518689   9.913528 -20.6  -0.2   9.3  17.20   26.6
mean_MIN_temp_C  1129.0  -3.685474   8.032294 -32.6 -10.1  -2.2   3.40    9.6
MEAN_TEMP_C      1129.0   2.419575   8.932659 -26.6  -5.2   3.5  10.30   17.9
extr_MAX_temp_C  1125.0  17.446222   9.459611  -7.2   8.3  18.3  26.10   34.4
extr_MIN_temp_C  1125.0 -14.470133  13.364296 -51.1 -26.1 -10.6  -2.20    5.0
total_rain_mm    1127.0  23.400355  28.514200   0.0   0.8  11.4  36.80  152.7
total_snow_cm    1127.0  17.791571  21.487184   0.0   0.0  11.7  26.85  157.0
total_precip_mm  1127.0  39.491748  27.123389   0.0  20.1  32.5  52.30  193.8

In [12]:
#data[data == np.inf].count()
# drop rows with all zeros
data = data.loc[(df!=0).any(1)]

<ipython-input-12-7e55de5b4286>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  data = data.loc[(df!=0).any(1)]

In [13]:
#data.isna().sum().sum()
data = data.dropna()

In [14]:
data.isna().sum()

date_time          0
mean_MAX_temp_C    0
mean_MIN_temp_C    0
MEAN_TEMP_C        0
extr_MAX_temp_C    0
extr_MIN_temp_C    0
total_rain_mm      0
total_snow_cm      0
total_precip_mm    0
dtype: int64

In [15]:
data.shape

(1125, 9)

In [16]:
data["date_time"] = pd.to_datetime(data["date_time"])
data.set_index(data["date_time"], inplace=True)
data.drop("date_time", axis=1, inplace=True)

In [38]:
cleaned_data = data

In [53]:
cleaned_data.dtypes

mean_MAX_temp_C    float64
mean_MIN_temp_C    float64
MEAN_TEMP_C        float64
extr_MAX_temp_C    float64
extr_MIN_temp_C    float64
total_rain_mm      float64
total_snow_cm      float64
total_precip_mm    float64
dtype: object

In [ ]:
# reference: https://stackoverflow.com/questions/56858924/multivariate-input-lstm-in-pytorch

In [19]:
import torch

In [21]:
class MV_LSTM(torch.nn.Module):
    def __init__(self,n_features,seq_length):
        super(MV_LSTM, self).__init__()
        self.n_features = n_features
        self.seq_len = seq_length
        self.n_hidden = 20 # number of hidden states
        self.n_layers = 1 # number of LSTM layers (stacked)
    
        self.l_lstm = torch.nn.LSTM(input_size = n_features, 
                                 hidden_size = self.n_hidden,
                                 num_layers = self.n_layers, 
                                 batch_first = True)
        # according to pytorch docs LSTM output is 
        # (batch_size,seq_len, num_directions * hidden_size)
        # when considering batch_first = True
        self.l_linear = torch.nn.Linear(self.n_hidden*self.seq_len, 1)
        
    
    def init_hidden(self, batch_size):
        # even with batch_first = True this remains same as docs
        hidden_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        cell_state = torch.zeros(self.n_layers,batch_size,self.n_hidden)
        self.hidden = (hidden_state, cell_state)
    
    
    def forward(self, x):        
        batch_size, seq_len, _ = x.size()
        
        lstm_out, self.hidden = self.l_lstm(x,self.hidden)
        # lstm_out(with batch_first = True) is 
        # (batch_size,seq_len,num_directions * hidden_size)
        # for following linear layer we want to keep batch_size dimension and merge rest       
        # .contiguous() -> solves tensor compatibility error
        x = lstm_out.contiguous().view(batch_size,-1)
        return self.l_linear(x)

In [43]:
from numpy import array
from numpy import hstack
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [36]:
# define input sequence
in_seq1 = array([x for x in cleaned_data[0:1120:10]])
in_seq2 = array([x for x in cleaned_data[5:1125:10]])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

In [57]:
# initialization
n_features = 8 # this is number of parallel inputs
n_timesteps = 3 # this is number of timesteps

# convert dataset into input/output
X, y = split_sequences(dataset, n_timesteps)
print(X.shape, y.shape)

# create NN
mv_net = MV_LSTM(n_features,n_timesteps)
criterion = torch.nn.MSELoss() # reduction='sum' created huge loss value
optimizer = torch.optim.Adam(mv_net.parameters(), lr=1e-1)

train_episodes = 500
batch_size = 16

(6, 3, 2) (6,)

In [59]:
print(type(X))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [62]:
# train
mv_net.train()
for t in range(train_episodes):
    for b in range(0,len(X),batch_size):
        inpt = X[b:b+batch_size,:,:]
        target = y[b:b+batch_size]    
        
        x_batch = torch.tensor(inpt,dtype=torch.float64)    
        y_batch = torch.tensor(target,dtype=torch.float64)
    
        mv_net.init_hidden(x_batch.size(0))
    #    lstm_out, _ = mv_net.l_lstm(x_batch,nnet.hidden)    
    #    lstm_out.contiguous().view(x_batch.size(0),-1)
        output = mv_net(x_batch) 
        loss = criterion(output.view(-1), y_batch)  
        
        loss.backward()
        optimizer.step()        
        optimizer.zero_grad() 
    print('step : ' , t , 'loss : ' , loss.item())

TypeError: ignored